/// ============================================================
/// ACTIVITY MODEL
/// ============================================================
///
/// 🏗️ OFFICIAL HIERARCHY:
///   Farm / Entity → Field / Block → Crop or Livestock → Activity → Report
///
/// Schema source (farm_management.activities):
///   - id (uuid) — auto-generated by backend
///   - activity_type_id (uuid, required)
///   - performed_at (timestamptz, required)
///   - notes (text, nullable)
///   - entity_id (uuid, backend default)
///   - asset_id (uuid, nullable)
///   - plan_id (uuid, nullable)
///   - created_at (timestamptz, backend default)
///   - updated_at (timestamptz, backend default)
///   - is_deleted (boolean, default false)
///   - deleted_at (timestamptz, nullable)
///
/// ⚠️ NOTE: This model includes UI context fields (farmId, fieldId,
/// cropOrLivestockId, cropOrLivestockType) that are NOT persisted to the
/// activities table. They are used for frontend hierarchy enforcement,
/// form validation, and provider filtering only. The actual backend
/// relationship between an activity and field/crop is resolved through
/// the asset_id or plan_id linked entities.
/// ============================================================

// ignore_for_file: dangling_library_doc_comments

/// Represents a single row from `farm_management.activities` plus relevant fields
/// needed by the UI.
class ActivityModel {
  final String id;
  final String activityTypeId;

  /// 👇 UI HIERARCHY CONTEXT (NOT persisted to activities table)
  /// These fields are used for frontend context only — form validation,
  /// breadcrumb display, and provider filtering. The backend schema
  /// does NOT have farm_id, field_id, crop_or_livestock_id, or
  /// crop_or_livestock_type columns on the activities table.
  final String? farmId;
  final String? fieldId;
  final String? cropOrLivestockId;
  final String? cropOrLivestockType;

  final DateTime performedAt;
  final String? notes;
  final String? assetId;
  final String? planId;

  /// Dynamic attribute values collected during workflow execution.
  /// These are persisted to activity_values table.
  final Map<String, dynamic> attributeValues;

  const ActivityModel({
    required this.id,
    required this.activityTypeId,
    this.farmId,
    this.fieldId,
    this.cropOrLivestockId,
    this.cropOrLivestockType,
    required this.performedAt,
    this.notes,
    this.assetId,
    this.planId,
    this.attributeValues = const {},
  });

  /// Create a copy with updated fields
  ActivityModel copyWith({
    String? id,
    String? activityTypeId,
    String? farmId,
    String? fieldId,
    String? cropOrLivestockId,
    String? cropOrLivestockType,
    DateTime? performedAt,
    String? notes,
    String? assetId,
    String? planId,
    Map<String, dynamic>? attributeValues,
  }) {
    return ActivityModel(
      id: id ?? this.id,
      activityTypeId: activityTypeId ?? this.activityTypeId,
      farmId: farmId ?? this.farmId,
      fieldId: fieldId ?? this.fieldId,
      cropOrLivestockId: cropOrLivestockId ?? this.cropOrLivestockId,
      cropOrLivestockType: cropOrLivestockType ?? this.cropOrLivestockType,
      performedAt: performedAt ?? this.performedAt,
      notes: notes ?? this.notes,
      assetId: assetId ?? this.assetId,
      planId: planId ?? this.planId,
      attributeValues: attributeValues ?? this.attributeValues,
    );
  }
}