name: famhub_app
description: A new Flutter project for FamHub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Backend & Real-time
  supabase_flutter: ^2.12.0

  # UI Components & Data Visualization
  fl_chart: ^0.66.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  
  # Location Services
  geolocator: ^13.0.1

  # Local Persistence - NoSQL (Fast State/Preferences)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local Persistence - SQL (Relational/Heavy Tech Data)
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.5+1
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/